---
# # tasks file for deploy_promgrafnode
- name: Remove old Docker repository
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable'
    state: absent

- name: Download Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /etc/apt/keyrings/docker.gpg

- name: Create /etc/apt/keyrings directory if it does not exist
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker's APT repository
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable'
    state: present

- name: Update and upgrade all packages to the latest version
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600

- name: Install Docker and related packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: Add Docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /usr/local/bin/docker-compose
    owner: ubuntu
    group: ubuntu

- name: Enable and start Docker services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - docker.service
    - containerd.service

- name: Create necessary directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: ubuntu  
    group: ubuntu  
    mode: '0777'
  loop:
    - "{{ destin_folder }}/prometheus"
    - "{{ destin_folder }}/alertmanager"
    - "{{ destin_folder }}/blackbox-exporter"
    - "{{ destin_folder }}/grafana/provisioning/datasources"
    - "{{ destin_folder }}/grafana/provisioning/dashboards"

- name: Copy Docker Compose file
  copy:
    src: docker-compose-vm2.yml
    dest: "{{ destin_folder }}/docker-compose.yml"
    owner: ubuntu
    group: ubuntu

- name: Copy ENV file
  copy:
    src: .env
    dest: "{{ destin_folder }}/.env"
    owner: ubuntu
    group: ubuntu
    
- name: Copy grafana datasources file
  copy:
    src: grafana_datasources.yml
    dest: "{{ destin_folder }}/grafana/provisioning/datasources/prometheus.yml"
    owner: ubuntu
    group: ubuntu

- name: Copy configuration dashboards files
  copy:
    src: "{{ item.src }}"
    dest: "{{ destin_folder }}/grafana/provisioning/dashboards/{{ item.dest }}"
    owner: ubuntu
    group: ubuntu
  loop:
    - { src: 'blackbox_exporter.json', dest: 'blackbox_exporter.json' }
    - { src: 'dashboards.yml', dest: 'dashboards.yml' }
    - { src: 'node_exporter_full.json', dest: 'node_exporter_full.json' }

- name: Copy configuration files
  copy:
    src: "{{ item.src }}"
    dest: "{{ destin_folder }}/prometheus/{{ item.dest }}"
    owner: ubuntu
    group: ubuntu
  loop:
    - { src: 'prometheus.yml', dest: 'prometheus.yml' }
    - { src: 'alert_rules.yml', dest: 'alert_rules.yml' }

- name: Copy alert config file
  copy:
    src: alert_rules.yml
    dest: "{{ destin_folder }}/alertmanager/alert-config.yml"
    owner: ubuntu
    group: ubuntu

- name: Copy blackbox config file
  copy:
    src: blackbox-exporter-config.yml
    dest: "{{ destin_folder }}/blackbox-exporter/blackbox-exporter-config.yml"
    owner: ubuntu
    group: ubuntu

- name: Run Docker Compose
  shell: docker-compose -f {{ destin_folder }}//docker-compose.yml up -d
  become: true
  become_user: ubuntu