---
# tasks file for deploy_exporters
# - name: Update and upgrade all packages to the latest version
#   ansible.builtin.apt:
#     update_cache: true
#     upgrade: dist
#     cache_valid_time: 3600

# - name: Install required packages
#   ansible.builtin.apt:
#     pkg:
#       - apt-transport-https
#       - ca-certificates
#       - curl
#       - gnupg
#       - software-properties-common

- name: Remove old Docker repository
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable'
    state: absent

- name: Download Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /etc/apt/keyrings/docker.gpg

- name: Create /etc/apt/keyrings directory if it does not exist
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker's APT repository
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable'
    state: present

- name: Update and upgrade all packages to the latest version
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600


- name: Install Docker
  ansible.builtin.apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Add Docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /usr/local/bin/docker-compose
    owner: ubuntu
    group: ubuntu

- name: Enable and start Docker services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - docker.service
    - containerd.service

- name: Create necessary directories
  ansible.builtin.file:
    path: /home/ubuntu/promgrafnode
    state: directory
    mode: '0755'
  

- name: Copy Docker Compose file
  copy:
    src: docker-compose-vm1.yml
    dest: "{{ destin_folder }}/docker-compose.yml"

- name: Remove existing Docker containers
  docker_container:
    name: "{{ item }}"
    state: absent
  loop:
    - node-exporter
    - cadvisor

- name: Run Docker Compose
  shell: docker-compose -f  {{ destin_folder }}/docker-compose.yml up -d